version: '3'

services:
  mysql:
    image: mysql:5.7.23
    hostname: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timeSheetDevOps
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3366:3306"
